FROM node:12
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
# Disable to new machine
COPY node_modules ./node_modules
COPY src ./src
RUN ls -a
# RUN npm install
EXPOSE 8080
CMD ["npm","run","dev"]