FROM node:12.22.10
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
# Disable to new machine
COPY node_modules ./node_modules
COPY src ./src
COPY views ./views
COPY public ./public
RUN ls -a
RUN npm install
EXPOSE 8080
CMD ["npm","run","dev"]